apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-server
  labels:
    app: oauth2-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-server
  template:
    metadata:
      labels:
        app: oauth2-server
    spec:
      containers:
      - name: oauth2-server
        image: oauth2-server:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: JWT_SIGNATURE_KEY
          valueFrom:
            secretKeyRef:
              name: jwt-key
              key: private-key
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: oauth2-server
  annotations:
    k3d.io/loadbalancer.port: "8080:8080"
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: oauth2-server
