name: 'Go Module Cache'
description: 'Cache Go modules for monorepo structure'

runs:
  using: "composite"
  steps:
    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/go/pkg/mod
          ${{ github.workspace }}/keytool/go.sum
          ${{ github.workspace }}/server/go.sum
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
