name: Basic Branch Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Install golangci-lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.57.2
        $(go env GOPATH)/bin/golangci-lint --version

    - name: Run linting
      run: |
        make lint || if [ "${{ github.event_name }}" != "push" ] || [ "${{ github.ref }}" = "refs/heads/main" ]; then
          exit 1
        fi

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Build Keytool
      working-directory: keytool
      run: go build -v ./...

    - name: Test Keytool
      working-directory: keytool
      run: go test -v ./...

    - name: Build Server
      working-directory: server
      run: go build -v ./...

    - name: Test Server
      working-directory: server
      run: go test -v ./...
