name: Reusable Go Cache

on:
  workflow_call:

jobs:
  cache:
    name: Cache Go Modules
    runs-on: ubuntu-latest
    steps:
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            keytool/go.sum
            server/go.sum
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
